---
kind: pipeline
type: docker
name: python3.8

steps:
  - name: build
    image: python:3.8
    commands:
      - pip install --no-cache-dir -r requirements.txt
      - pip install --no-cache-dir trytond
      - sphinx-build . docs

---
kind: pipeline
type: docker
name: python3.7

steps:
  - name: build
    image: python:3.7
    commands:
      - pip install --no-cache-dir -r requirements.txt
      - pip install --no-cache-dir trytond
      - sphinx-build . docs

---
kind: pipeline
type: docker
name: python3.6

steps:
  - name: build
    image: python:3.6
    commands:
      - pip install --no-cache-dir -r requirements.txt
      - pip install --no-cache-dir trytond
      - sphinx-build . docs

---
kind: pipeline
type: docker
name: python3.5

steps:
  - name: build
    image: python:3.5
    commands:
      - pip install --no-cache-dir -r requirements.txt
      - pip install --no-cache-dir trytond
      - sphinx-build . docs
